### ISSUE TITLE
archive the repo?

### ISSUE THREAD

**Issue by aladdin-add** [eslint/cn.eslint.org#238]
The repo has not received any updates for several years, and new updates should be in the new repo: `eslint/zh-hans.docs.eslint.org`.

cc @kecrily

**Comment by kecrily** [comment]
OMG, I didn't notice that this repository hadn't been archived yet. Yes, we should archive it, and maybe change the README a bit to add some notes before archiving it.

I don't have permission to archive it though, can you do that?

**Comment by aladdin-add** [comment]
I haven't either 😅. we will have to ask @eslint/eslint-tsc to do it. /cc @mdjermanovic  

can you send a PR to change the README? :)

**Comment by nzakas** [comment]
I'll archive the repo now.
