### ISSUE TITLE
The future of this project?

### ISSUE THREAD

**Issue by kaicataldo** [eslint/cn.eslint.org#27]
This site is currently out of sync with the main website, and the current strategy of manually updating it once in a while doesn't seem sustainable. I think we should decide what our end goal is, since this repository is in our org.

I'm assuming we'll want to keep this repo active until we figure out and implement [translating the main eslint.org website](https://github.com/eslint/eslint/issues/11512), but since we haven't discussed this in a long time, wanted to make sure we decide as a team what we'd like to do.

cc @eslint/eslint-team

**Comment by g-plane** [comment]
I think we should setup translation service for main website as soon as possible, since maintaining two websites isn't easy.

**Comment by QC-L** [comment]
Hello, everyone. I'm QiChang Li from china. I work for [docschina](https://github.com/docschina). And I work on several open source projects for Chinese documentation, e.g. [react](https://github.com/reactjs/zh-hans.reactjs.org), [webpack](https://github.com/docschina/webpack.js.org), [vite](https://github.com/vitejs/docs-cn), etc...
Recently, some of our partners said that the Chinese documentation of eslint is too old. I think we can keep it up and update it with English.

We have a complete set of synchronization and maintenance solutions for Chinese documents.

I look forward to hearing from you!

**Comment by nzakas** [comment]
Hi @QC-L we would love the help. What do you have in mind?

**Comment by QC-L** [comment]
I want to maintain this repository and keep it up to date with English.

I need to be given basic access to the repository so I can invite people to maintain it. Also, I will add [docschina-bot](https://github.com/docschina-bot) for automatic synchronization.

Give me access and leave the rest to me. I will organize translators to do the translation.

**Comment by nzakas** [comment]
Sorry for the delay in replying. Can you explain more about what the process would be for keeping the docs up to date and what type of access you would need?

In general, we don’t like giving admin access on our repos to people we don’t know, so I’d like to understand a little more about your process.

**Comment by QC-L** [comment]
Right.

Let me introduce the process. 

1. Create a new branch based on the latest English documentation, and perform subsequent maintenance on this branch
2. Based on this branch access to bot, complete with regular updates (weekly/daily)
3. Re-translation based on existing Chinese documents to ensure consistency with English

You can refer to [React Conf's i18n Solutions for reactjs.org](https://conf.reactjs.org/event.html?tesseralis) for more details on the process.

I'm currently the maintainer of zh-hans.reactjs.org

## About Permissions

You can give me maintainer access and docschina-bot write access.

**Comment by nzakas** [comment]
Okay thanks, let me run this by the team to see what they think.

**Comment by nzakas** [comment]
Sorry for the delay, we will set you up with permissions for the repo and see how it goes. Thanks for the offer. :)

**Comment by nzakas** [comment]
Okay, I’ve invited you to the team. Please let me know if the permissions are setup correctly.

**Comment by QC-L** [comment]
Sorry, I'm late, I found out that the invitation has expired. Please invite again. Thanks

**Comment by nzakas** [comment]
Just re-sent the invite

**Comment by QC-L** [comment]
Joined, but not enough permissions to invite bots and partners.

**Comment by nzakas** [comment]
I had to wait for you to accept the invite before I could set your role. You should have permissions now.

**Comment by nzakas** [comment]
There is no master branch, only main, but the site is in gh-pages.

**Comment by QC-L** [comment]
![image](https://user-images.githubusercontent.com/13861040/127586191-5ac429ca-b0ab-4819-b80e-3a50fc192c5a.png)
No permission.

**Comment by QC-L** [comment]
> There is no master branch, only main, but the site is in gh-pages.

Sorry, that should be the main branch. Because it has to be synchronized with the eslint/website, its structure should be consistent with the eslint/website.

**Comment by nzakas** [comment]
@QC-L I’m not sure what the screenshot is showing me. What is it you are expecting to be there that isn’t?

**Comment by QC-L** [comment]
![image](https://user-images.githubusercontent.com/13861040/127729883-96045f1e-473f-4095-9456-ee4d7a69eedf.png)

**Comment by nzakas** [comment]
I have you in the Chinese-docs group, which has “Maintain” role on the repo. You should be able to add anyone you want to the Chinese-Docs group and they will have the same permissions. 

![1897F46F-18A9-45C4-B6B5-38269367DA02](https://user-images.githubusercontent.com/38546/127940260-f3518bec-4e6d-4c12-b209-ce77380f2bdb.png)

**Comment by QC-L** [comment]
This is not possible, because this permission can only invite people already in the organization, and cannot invite people outside the organization. The example is as follows：

![image](https://user-images.githubusercontent.com/13861040/127947430-a04dbdbc-d134-44c1-a5d2-1b3c7d384741.png)

**Comment by QC-L** [comment]
The last thing, please adjust the branch, adjust the main branch to be the master branch and I will push the main branch build to gh-pages

**Comment by nzakas** [comment]
> First, please adjust the branch, adjust the main branch to be the master branch and I will push the main branch build to gh-pages.

can you explain this a bit more? I’m having trouble understanding what you’re asking for. Right now gh-pages is where the website is built from. Where do you want it to build from?

**Comment by nzakas** [comment]
I’ve invited @ivocin and @knowscount

**Comment by QC-L** [comment]
It is built in the same way as eslint/website, as the Chinese documentation is now lagging behind the website site. So to ensure consistency, at the same time I can ensure that the Chinese and English can be synchronized in time through bot.

Currently, the frequency of synchronization is once a day.

**Comment by QC-L** [comment]
> I’ve invited @Ivocin and @KnowsCount

Thanks！

**Comment by nzakas** [comment]
Right now gh-pages is where the website is built from. Where do you want it to build from? Are you saying you want it to be built from "main"?

eslint/website is currently built from "master", but we will be changing that to "main" in the near future.

**Comment by QC-L** [comment]
> Are you saying you want it to be built from "main"?

Yes. We will build from the main branch. 

> eslint/website is currently built from "master", but we will be changing that to "main" in the near future.

Your branch changes will not affect us. At most, it will only affect synchronization.

**Comment by QC-L** [comment]
![image](https://user-images.githubusercontent.com/13861040/128391972-ee73a9f0-0102-498e-a767-3ece28ba867c.png)

I think I may have misrepresented it, I just want you to change the default branch to main.

**Comment by nzakas** [comment]
Ah okay. I just set the default branch to "main". Let me know if you need anything else.

**Comment by QC-L** [comment]
@nzakas Thanks!

**Comment by QC-L** [comment]
I will close this issue and open a new one later!

**Comment by nzakas** [comment]
Sounds good. Thanks for the help and patience. If you need anything else, open a new issue and be sure to @-mention me, as I'm going to turn off notifications for everything you're doing.

**Comment by QC-L** [comment]
@nzakas Okay, if I need your help, I will contact you. Thanks！
