### ISSUE TITLE
eslint.cn has no maintaining for a long time.

### ISSUE THREAD

**Issue by Aladdin-ADD** [eslint/cn.eslint.org#3]
eslint.cn has no maintaining for a long time.
Is someone working on this? My friends and I have experience in translating webpack and make it deploy automatically. or we can do something, to help more Chinese users?

Looking forward to your reply. 😄

**Comment by not-an-aardvark** [comment]
Thanks for being willing to help!

We have an @eslint/eslint-docs team that has access to this repository. Would you be interested in getting added to that team?

I'm not sure whether there's a process that I need to follow for adding people -- pinging @eslint/eslint-tsc to confirm.

**Comment by Aladdin-ADD** [comment]
That would be great~

**Comment by kaicataldo** [comment]
We would definitely love your help! Do you have any ideas about how we could go about doing this?

**Comment by Aladdin-ADD** [comment]
Now we have a group of ~150, mostly front-end developers.

To get started, we can work out a guide to join the translation, including:
- build & testing & deploy
- process of translation & review..
- faq,etc

Do we have a maintainer guide about this repo?

**Comment by kaicataldo** [comment]
I honestly don't know how this was done in the past. @eslint/eslint-team Anyone have any ideas?

**Comment by ilyavolodin** [comment]
There's only one person that was added to maintain this repository. He reached out to us, and offered help with creating/maintaining chines version of the site, and was given permissions to do so. So there's really no process behind it, I think. If @Aladdin-ADD wants to take over, I think that's perfectly fine. We do not have any maintainer guide for this repo. Unfortunately, nobody from the core team has been involved in working on this repo, so you might have to start from the scratch.

**Comment by Aladdin-ADD** [comment]
I see. I think I can be a maintainer. 😄

**Comment by not-an-aardvark** [comment]
I sent you an invitation to join the @eslint/eslint-docs team.

**Comment by molee1905** [comment]
sorry for delay such a long time,  i'll check my time to update it to latest version. very glad to  see @Aladdin-ADD to get involed in,  you can  contact me var [eslint中文](http://weibo.com/eslint)

**Comment by Aladdin-ADD** [comment]
🤝 so good to see u. @molee1905 
would you give some info to async from eslint.github.io? as eslint@4.0.0 released, we have things to do.

**Comment by molee1905** [comment]
To ensure the highest consistency of the original text and accurate translation when updating, add the translated text below original text sentence by sentence, just update original text, and then update translated text. There may be a more efficient way to do so, but i think this is the best way to keep in sync with eslint.org and never lose the true meaning

**Comment by molee1905** [comment]
ESLint  v4.0.0  doc in Chinese version has been released !

**Comment by Aladdin-ADD** [comment]
thanks for doing this. ❤️
